name: lint
on: [push, pull_request]
jobs:
  golangci-lint:
    name: lint library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
        with:
          version: v1.29.0